### PR TITLE
Update Tokens.js, iOS no longer work.

### PR DESCRIPTION
**Pull request by Beat-YT**

### CODE REVIEW

**Comment by Beat-YT** [comment]
So app dont crash

**Comment by ThisNils** [comment]
The program crashes? Could you tell me what exactly the error was?

**Comment by AlexT2** [comment]
Why did you replace the IOS token with the windows one lol

**Comment by Beat-YT** [comment]
It's cuz the iOS token not valid. Epic removed it

**Comment by ThisNils** [comment]
Epic did not remove the IOS token. Tell me how to reproduce the issue and i might be able to resolve it

**Comment by Beat-YT** [comment]
Ok

**Comment by ThisNils** [comment]
Open an issue with your problem if it still exists

**Pull request closed without merging**
