### PR TITLE
add PartyMember#playlist, update Party#playlist getters and fix Party#setPlaylist method

### PR DESCRIPTION
**Pull request by tnfAngel**
[add PartyMember#island getter](https://github.com/fnbrjs/fnbr.js/pull/739/commits/e80221d50677b8a119cd1c38843f58750b6fc406)
[add Party#island getter](https://github.com/fnbrjs/fnbr.js/pull/739/commits/1bdb24793ff8002e02f66b58b0a5c83bdf4a78de)
This is a new meta field added by Epic Games and refers to selected islands and playlists

### CODE REVIEW

**Comment by tnfAngel** [comment]
Default:CurrentIsland_j
Default:CurrentIsland_j

Default:SelectedIsland_j
Default:SelectedIsland_j

**Comment by tnfAngel** [comment]
solves #737

**Comment by LeleDerGrasshalmi** [comment]
> but you are missing `bIsWorldJoinable` in `joinInfo`
(talk from discord)

**Review by ThisNils — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
