### PR TITLE
Implement Client#stw

### PR DESCRIPTION
**Pull request by tnfAngel**
I don't know if that's all, but it's a good start

### CODE REVIEW

**Comment by tnfAngel** [comment]
stw news api has changed (Discord, from @LeleDerGrasshalmi)

**Comment by tnfAngel** [comment]
Oh I accidentally messed it up

**Comment by tnfAngel** [comment]
I'll fix it

**Comment by ThisNils** [comment]
Let's handle the stw news issue in a separate PR

**Review by ThisNils — APPROVED** [review]

**Pull request merged**
